CREATE TABLE USUARIO_TIPO(
	ID INT IDENTITY PRIMARY KEY,
	DESCRICAO VARCHAR(250)
)

CREATE TABLE USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250),
	EMAIL VARCHAR(250),
	SENHA VARCHAR(20),
	TIPO_ID INT,
	CONSTRAINT FK_USUARIO_USUARIO_TIPO FOREIGN KEY (TIPO_ID) REFERENCES USUARIO_TIPO (ID)
)

CREATE TABLE PONTO(
	USUARIO_ID INT,
	DATA_REGISTRO DATETIME,
	TIPO_REGISTRO INT,
	CONSTRAINT FK_PONTO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID)
)

CREATE TABLE PAGAMENTO(
	ID INT IDENTITY PRIMARY KEY,
	USUARIO_ID INT,
	DATA_PAGAMENTO DATE,
	VALOR_PAGAMENTO NUMERIC(8,2),
	CONSTRAINT FK_PAGAMENTO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID)
)

/*DATA MOCK*/

INSERT INTO USUARIO_TIPO VALUES 
('Diretor'),
('Funcionario'),
('RH')

INSERT INTO USUARIO VALUES
('Desenvolvedor','dev@mail.com','xpto123',2)

INSERT INTO PAGAMENTO VALUES
(1, CAST(GETDATE() AS DATE), 1750.95)